apiVersion : apps/v1
kind: Deployment
metadata:
  name: k8sapptest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sapptest
  template:
    metadata:
      labels:
        app: k8sapptest 
    spec:
      containers:
        - name: k8sapptest 
          image: acontainerregistry.azurecr.io/k8sapptest
          ports:
          - containerPort: 8